version: '3'
services:
  couchdb:
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default
  proxy:
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default
  flower:
    networks:
      - {{cookiecutter.traefik_public_network}}
      - default

networks:
  {{cookiecutter.traefik_public_network}}:
    external: true
