version: '3'
services:
  couchdb:
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  backend:
    environment:
      - SERVER_NAME=${DOMAIN}
      - SECRET_KEY={{cookiecutter.secret_key}}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - COUCHDB_SERVER=${COUCHDB_SERVER}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_CORS_ORIGINS=${COUCHDB_CORS_ORIGINS}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
  celeryworker:
    environment:
      - SENTRY_DSN={{cookiecutter.sentry_dsn}}
      - COUCHDB_SERVER=${COUCHDB_SERVER}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_CORS_ORIGINS=${COUCHDB_CORS_ORIGINS}
      - FIRST_SUPERUSER={{cookiecutter.first_superuser}}
      - FIRST_SUPERUSER_PASSWORD={{cookiecutter.first_superuser_password}}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
